### ISSUE TITLE
Unity500 works properly

### ISSUE THREAD

**Issue by elisalepida** [ImTheLucKyOne/check_mk_emcunity#13]
i have just tested this agent on our Unity500 and both emcunity_fs and emcunity_lun return "UNKNOWN - invalid output from agent or error in check implementation"

**Comment by ImTheLucKyOne** [comment]
The checks have't been checked against a unity500 system yet. Which unity packet version and which cmk version do you use?

Please run on your cmk server `cmk -vv --debug -II HOST` or if you already have services inventoried `cmk -vv --debug -d HOST`. Post the error here.

Additionally run this uemcli command and post the output here: `uemcli -d HOST -u user -p password /stor/prov/luns/lun show -detail`

**Comment by elisalepida** [comment]
Good news. I have a test virtual machine and two production virtual machines. I can't understand why but i have installed the same cmk version (1.5.0p11) and the same unity package version (2.2.0) and ONLY on the test virtual machine i have the error. In production this package works well for Unity500.
I'm still trying to understand the problem on the test machine, where both commands that you have suggested return all data without problems. Except for this strange problem i can comfirm that this package is ok also for Unity 500!
Thank you so much!

**Comment by ImTheLucKyOne** [comment]
Glad it works now. Thank you for confirming that.

**Comment by elisalepida** [comment]
Checked on Unity 600. All is ok!

**Comment by ImTheLucKyOne** [comment]
Nice, thank you very much.
