### ISSUE TITLE
1.6 not supported ?

### ISSUE THREAD

**Issue by cadencep45** [ImTheLucKyOne/check_mk_emcunity#19]
when you say

The latest version of the cmk package does not work with cmk versions < 1.6.0.

what specifically is broken ?

Why do I ask ?

Our monitoring team are making threatening noises to migrate to 1.6 and I want to alert them of impact to plugin and effort to fix.

**Comment by cadencep45** [comment]
call off the hounds :) complexities of > and < confused.

**Comment by ImTheLucKyOne** [comment]
Yeah, the latest package contains a change where python modules have to be imported explicitly for the metrics to work in 1.6. That import statement raises an error in cmk versions prior 1.6.
