### ISSUE TITLE
degraded pool / still in OK state

### ISSUE THREAD

**Issue by pdcemulator** [ImTheLucKyOne/check_mk_emcunity#21]
Hi,

one of my pools is degraded caused by a failed drive. But the pool state is still OK, I had expect a WARN state.

Service State: OK
Service Output: OK - 27.87% used (xx of xx TB), trend: +x GB / 24 hours, subscription: 64%, EMC State: Degraded/Warning (10) "The pool is currently degraded, and does not have enough spare space to initiate a rebuild. Replace the faulted drive, or add a drive of the same type and size or larger to the system."

I had a look into the check source, and it does not check the pool state. But this should be checked. According to the docs, the following health states are possible:
* Unknown (0) — Status is unknown.
* OK (5) — Working correctly.
* OK BUT (7) — Working correctly, but there could be a problem.
* Degraded/Warning (10) — Working and performing all functions, but the performance may not be optimum.
* Minor failure (15) — Working and performing all functions but overall performance is degraded. This condition has a minor * impact on the system and should be remedied at some point, but does not have to be fixed immediately.
* Major failure (20) — Failing and some or all functions may be degraded or not working. This condition has a significant impact * on the system and should be remedied immediately.
* Critical failure (25) — Failed and recovery may not be possible. This condition has resulted in data loss and should be remedied immediately.
* Non-recoverable error (30) — Completely failed and cannot be recovered.

My ENV
* cmk EE 1.6p13
* EMC Unity 350F 5.0.0.0.5.116
* cmk_emcunity 2.2.2

**Comment by ImTheLucKyOne** [comment]
Hi,

I can not merge your request because the plugin uses the df_check_filesystem function to calculate the state like other filesystem checks do (with all the levels and stuff).
But I will implement parse_emcstate to override the df state if emcstate is worse than df state.

Thank you for the report!

**Comment by ImTheLucKyOne** [comment]
I changed the filesystem checks _lun, _pool and _vmfs.

**Comment by pdcemulator** [comment]
> I can not merge your request because the plugin uses the df_check_filesystem function to calculate the state like other filesystem checks do (with all the levels and stuff).

Just for information...
I used the yield instead of return function. With yield, you are able to submit multiple "results" (status, output, performance values) for a single service. For example one for the status, a second for file system usage.
Cmk uses the worst state as the final service state and the output get concattinated. You dont have to do this yourself in the check. This leads better readable check functions because you can seperate different things to check.
