### ISSUE TITLE
FC-Connection Status

### ISSUE THREAD

**Issue by wernermarcel1** [ImTheLucKyOne/check_mk_emcunity#7]
Hello, 

is it possible to implement a FC Connection Status Check ? 

thx 
rg
marcel

**Comment by ImTheLucKyOne** [comment]
Hi Marcel,

yes I think it is possible to add a FC check. I will have a look at the info the uemcli provides and keep you up to date here.

**Comment by wernermarcel1** [comment]
Hi ,

thanks a lot I can test it against 300F  and 450F.

rg
marcel


Von: Philipp N. [mailto:notifications@github.com]
Gesendet: Montag, 9. April 2018 10:58
An: ImTheLucKyOne/check_mk_emcunity <check_mk_emcunity@noreply.github.com>
Cc: Werner, Marcel <Marcel.Werner@P7S1Produktion.de>; Author <author@noreply.github.com>
Betreff: Re: [ImTheLucKyOne/check_mk_emcunity] FC-Connection Status (#7)


Hi Marcel,

yes I think it is possible to add a FC check. I will have a look at the info the uemcli provides and keep you up to date here.

**Comment by wernermarcel1** [comment]
Hi,

I look for information if the port is healthy and it would be nice if in the status line I ccan see the speed, and the health details.


1:    ID                      = spa_fc4
      Name                    = SP A FC Port 4
      SP                      = spa
      Speed                   = 8 Gbps
      Requested speed         =
      Available speeds        = 4 Gbps, 8 Gbps, 16 Gbps, auto
      Health state            = OK (5)
      Health details          = "The port is operating normally."
      Connector type          = LC
      SFP supported speeds    = 4 Gbps, 8 Gbps, 16 Gbps
      SFP supported protocols = FibreChannel
      Replication capability  = Sync replication
      SFP supported mode      = MultiMode


Rg
Marcel

Von: Philipp N. [mailto:notifications@github.com]
Gesendet: Montag, 9. April 2018 11:21
An: ImTheLucKyOne/check_mk_emcunity <check_mk_emcunity@noreply.github.com>
Cc: Werner, Marcel <Marcel.Werner@P7S1Produktion.de>; Author <author@noreply.github.com>
Betreff: Re: [ImTheLucKyOne/check_mk_emcunity] FC-Connection Status (#7)


Please run uemcli -d IP -u user -p password /net/port/fc show -detail and tell me if that is the information about the FC ports you are looking for.

**Comment by wernermarcel1** [comment]
is it possible that you forgot  to include the new check in “agent_emcunity” ?

Von: Philipp N. [mailto:notifications@github.com]
Gesendet: Montag, 9. April 2018 14:38
An: ImTheLucKyOne/check_mk_emcunity <check_mk_emcunity@noreply.github.com>
Cc: Werner, Marcel <Marcel.Werner@P7S1Produktion.de>; Author <author@noreply.github.com>
Betreff: Re: [ImTheLucKyOne/check_mk_emcunity] FC-Connection Status (#7)


I just uploaded the fc check and checkman. Try it out. For me it worked so far ;)
