### ISSUE TITLE
Host Object Support (Degreaded/Warning)

### ISSUE THREAD

**Issue by wernermarcel1** [ImTheLucKyOne/check_mk_emcunity#9]
Please make possible that we get one Check thats include all HostObjects as MultiLine with the coresponding status. 

If one of the Hosts has an Status Warning the complete Check goes to warning. 

The Multilineoutput: 
Hostname OK
Hostname Warning
Hostname Critical 

Get the Status of the Host : 
uemcli  -d XXX  -u ‘XXX’  -p 'XXX'  /remote/host show -brief

Some examples : 

9:    ID              = Host_9
      Name            = XXXX-02
      Description     = 
      Tenant          = 
      Type            = host
      Address         = 
      Netmask         = 
      OS type         = Windows Server
      Ignored address = 
      Health state    = OK (5)
      Health details  = "The component is operating normally. No action is required."

8:    ID              = Host_8
      Name            = XXXX-01
      Description     = 
      Tenant          = 
      Type            = host
      Address         = 
      Netmask         = 
      OS type         = Windows Server
      Ignored address = 
      Health state    = Degraded/Warning (10)
      Health details  = "The host only has one path to the storage system. Add multiple paths between host and storage systems to establish redundancy."

**Comment by ImTheLucKyOne** [comment]
I added a new check and edited the agent code accordingly.

Thanks for the idea Marcel.
